"""empty message

Revision ID: 046b89049918
Revises: 385cbfd24343
Create Date: 2023-06-20 16:01:20.718476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046b89049918'
down_revision = '385cbfd24343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('seeking_venue')

    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('Shows_show_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])
        batch_op.drop_column('show_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Shows_show_id_fkey', 'Artist', ['show_id'], ['id'])
        batch_op.drop_column('artist_id')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
