"""empty message

Revision ID: 2baa4e876e73
Revises: 9b511e0641d7
Create Date: 2023-06-19 14:36:50.523140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2baa4e876e73'
down_revision = '9b511e0641d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('website_link')
        batch_op.drop_column('SeekingDescription')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('SeekingDescription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SeekingDescription', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('SeekingDescription', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('website_link', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
