"""empty message

Revision ID: 9b511e0641d7
Revises: 450a994fe380
Create Date: 2023-06-13 20:14:33.008871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b511e0641d7'
down_revision = '450a994fe380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('SeekingDescription', sa.String(length=120), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('website_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('SeekingDescription', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('SeekingDescription')
        batch_op.drop_column('website_link')
        batch_op.drop_column('genres')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('SeekingDescription')
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
